name: Check Notebook Standards

on:
  push:
    branches: [ "master" ]
    paths:
      - "notebooks/**/*.ipynb"
      - ".github/workflows/check_notebook_standards.yml"
      - "test/src/check_notebook_standards.py"
  pull_request:
    branches: [ "master" ]
    paths:
      - "notebooks/**/*.ipynb"
      - ".github/workflows/check_notebook_standards.yml"
      - "test/src/check_notebook_standards.py"

jobs:
  check_standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check notebook standards
        run: python test/src/check_notebook_standards.py
